apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: -cluster 
  annotations:
    argocd.argoproj.io/sync-wave: "360"
  namespace: cluster 
spec:
  clusterName: cluster
  clusterNamespace: cluster
  clusterLabels:
    cloud: vSphere
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true