apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: -pull-secret
  annotations:
    argocd.argoproj.io/sync-wave: "355"
    sealedsecrets.bitnami.com/namespace-wide: "true"
  namespace: cluster
spec: 
  data:
    .dockerconfigjson: AgB6Nvu9dMP7XqUYju7h6dnc2jpaE7jccctXzOCTMlHLFhTsjtlOfo1/J9pdD8YXb36IB9JQMWDCRY58LK6oDk/rXQAEMkF4SOAZLBtbVq0R6JmZVT8FRi2aNDJ8FH38Wzakf48RGYEpeqkr1k3j3QeH+2ILERYx/3W7ARufEntlHh2VcXHOeLqETJXtenP+1x8nc2QAFSdoKrNntnGNCAI+JI1Sty4UUEL8tkjR+w2wNbEwIuJ5O9ixAWjPNeIo8rMemUBirMNxhJ000pTYqfxN63O/EXszXNZQc5dCm7l2vUwZzVJwuyigz7MtW1IOGoUWzTHIrEOrf3mrNOAAUyahJ2TFE40QY0/B9xxkFHvunxKBaRPZ+2xKL5cc4JLn0x1/hk3McVRFmusn/yuqNIDcHw441xFJyMmqSXP9cneWn3sgFiGDFpgZT+p0PaLq8YUN6w30GwAJ1tHPzYCpW+fuI3RGOub5zNL71sZoB9PBnlwA2owr8FEJOAdnTPRj1Hc7jxcU3bbIACm7qu9Rmyh28MzaQWghbiYw2Kknufd8XaQuyj3gq6uj3ctgA0SzLso6hZBaDz1x0PMd/+I1iInQUuFR+bnprWZVpTpHUKqvqzqaH1jvnZUMV1HYfw/MTk8y+eYQXYNBvXhy+OuH7uASO9SHLy3sG+BisdmODG6orDUDrzDWLTIug4ydpsD6Hneq2Tcfikb7xAVGNotw
  template: 
    data: null
    metadata:
      name: -pull-secret
      namespace: cluster
    type: kubernetes.io/dockerconfigjson